title: Lorem Ipsum Web
baseURL: /
params:
  layout_type: boxed
  style: classic
  palette: blue
  mode: light
  base_font: serif
  header:
    type: header
    template: header
    title: Home
    logo: /images/osia.png
    logo_alt: DIY logo
    has_primary_nav: true
    primary_nav_links:
      - type: action
        template: action
        label: Events
        url: /events
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: Article
        url: '/article'
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: Gallery
        url: /gallery
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: Graviti
        url: '/graviti'
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
    has_secondary_nav: true
    secondary_nav_links:
      - type: action
        template: action
        label: About Us
        url: /about
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - style: primary
        label: Donate
        url: '#'
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
        type: ''
    has_anncmnt: true
    anncmnt_content: >-
      Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn
      More](/pricing/)**
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-features
  footer:
    type: footer
    template: footer
    logo: /images/osia.png
    logo_alt: DIY logo
    has_primary_nav: true
    primary_nav_title: Osia
    primary_nav_links:
      - type: action
        template: action
        label: Events
        url: /events
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: Gallery
        url: /gallery
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: Graviti
        url: /graviti
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
    has_secondary_nav: true
    secondary_nav_title: Article
    secondary_nav_links:
      - type: action
        template: action
        label: Berita Acara
        url: /article/category/berita-acara
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: Kata Ustadz
        url: /article/category/kata-ustadz
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: Pena Santri
        url: /article/category/pena-santri
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
    has_tertiary_nav: true
    tertiary_nav_title: Us
    tertiary_nav_links:
      - type: action
        template: action
        label: About Us
        url: /about
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
    has_social: false
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=diy&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
    links: []
  domain: 'https://spectacular-1c297.netlify.app'
  favicon: ''
taxonomies:
  tag: "tags"
  category: "categories"
  author: "author"
disableKinds:
  - RSS
markup:
  goldmark:
    renderer:
      unsafe: true
