title = "Website Name"
baseURL = "/"
disqusShortname = "spectacular-pages-dev"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
languageCode = "id"
disableKinds = [ "taxonomy", "term" ]
_template = "config"

[permalinks]
data = "/article/:sections[1:]/:slug"

[minify]
minifyOutput = true

[author]
name = "Ayasy"

[params]
layout_type = "boxed"
style = "classic"
palette = "blue"
mode = "light"
base_font = "sans-serif"
domain = "https://spectacular-1c297.netlify.app"
favicon = ""

  [params.header]
  type = "header"
  template = "header"
  title = "Home"
  logo = "/images/osia.png"
  logo_alt = "DIY logo"
  has_primary_nav = true
  has_secondary_nav = true
  has_anncmnt = true
  anncmnt_content = "Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn More](/pricing/)**"
  anncmnt_align = "left"
  anncmnt_is_home_only = true
  anncmnt_has_close = true
  anncmnt_id = "new-features"

  [params.footer]
  type = "footer"
  template = "footer"
  logo = "/images/osia.png"
  logo_alt = "DIY logo"
  has_primary_nav = true
  primary_nav_title = "Osia"
  has_secondary_nav = true
  secondary_nav_title = "Article"
  has_tertiary_nav = true
  tertiary_nav_title = "Us"
  has_social = false
  content = '&copy; Stackbit. All rights reserved. This Jamstack site was created with <a href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank" rel="noopener">Stackbit</a>. Create yours <a href="https://app.stackbit.com/create?theme=diy&utm_source=deployed-footer" target="_blank" rel="noopener">now</a>'
  links = [ ]

    [[params.footer.primary_nav_links]]
    type = "action"
    template = "action"
    label = "Events"
    url = "/events"
    style = "link"
    has_icon = false
    icon = ""
    icon_position = ""
    new_window = false
    no_follow = false

    [[params.footer.primary_nav_links]]
    type = "action"
    template = "action"
    label = "Gallery"
    url = "/gallery"
    style = "link"
    has_icon = false
    icon = ""
    icon_position = ""
    new_window = false
    no_follow = false

    [[params.footer.primary_nav_links]]
    type = "action"
    template = "action"
    label = "Graviti"
    url = "/graviti"
    style = "link"
    has_icon = false
    icon = ""
    icon_position = ""
    new_window = false
    no_follow = false

    [[params.footer.secondary_nav_links]]
    type = "action"
    template = "action"
    label = "Berita Acara"
    url = "/article/categories/berita-acara"
    style = "link"
    has_icon = false
    icon = ""
    icon_position = ""
    new_window = false
    no_follow = false

    [[params.footer.secondary_nav_links]]
    type = "action"
    template = "action"
    label = "Kata Ustadz"
    url = "/article/categories/kata-ustadz"
    style = "link"
    has_icon = false
    icon = ""
    icon_position = ""
    new_window = false
    no_follow = false

    [[params.footer.secondary_nav_links]]
    type = "action"
    template = "action"
    label = "Pena Santri"
    url = "/article/categories/pena-santri"
    style = "link"
    has_icon = false
    icon = ""
    icon_position = ""
    new_window = false
    no_follow = false

    [[params.footer.tertiary_nav_links]]
    type = "action"
    template = "action"
    label = "About Us"
    url = "/about"
    style = "link"
    has_icon = false
    icon = ""
    icon_position = ""
    new_window = false
    no_follow = false

[[menu.main]]
identifier = "events"
name = "Events"
url = "/events"
weight = 1

[[menu.main]]
identifier = "article"
name = "Article"
url = "/article"
weight = 2

[[menu.main]]
identifier = "quotes"
name = "Quotes"
url = "/article/categories/kata-ustadz/"
parent = "article"
weight = 1

[[menu.main]]
identifier = "penasantri"
name = "Pena Santri"
url = "/article/categories/pena-santri/"
parent = "article"
weight = 2

[[menu.main]]
identifier = "gallery"
name = "Gallery"
weight = 3

[[menu.main]]
identifier = "photos"
name = "Photos"
url = "/gallery"
parent = "gallery"
weight = 1

[[menu.main]]
identifier = "graviti"
name = "Graviti"
url = "/graviti"
parent = "gallery"
weight = 2

[[menu.main]]
identifier = "about"
name = "About Us"
url = "/about"
weight = 5

[[menu.main]]
identifier = "donate"
name = "Donate"
url = "#"
weight = 6

  [menu.main.params]
  button = true

[outputs]
home = [ "HTML", "RSS" ]

[taxonomies]
tag = "tags"
category = "categories"
author = "author"

[markup.goldmark.renderer]
unsafe = true
